stages:
  - pre_check
  - build
  - target_test

before_script:
  - source ${CI_PROJECT_DIR}/tools/ci/utils.sh
  - add_gitlab_ssh_keys

include:
  - '.gitlab/ci/rules.yml'
  - '.gitlab/ci/pre_check.yml'
  - '.gitlab/ci/build.yml'
